include $(TOPDIR)/rules.mk

PKG_VERSION:=v1.22.4-Mod
PKG_RELEASE:=2

LUCI_TITLE:=LuCI Support for Nikki TProxy
LUCI_DEPENDS:=+luci-base +nikki

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
