include $(TOPDIR)/rules.mk

PKG_VERSION:=1.22.3
PKG_RELEASE:=Mod

LUCI_TITLE:=LuCI Support for Nikki TProxy
LUCI_DEPENDS:=+luci-base +nikki

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
