name: release-nikki-tproxy-terbaru

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: ${{ matrix.arch }}-${{ matrix.branch }} build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - aarch64_generic
        branch:
          - openwrt-24.10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build package
        uses: openwrt/gh-action-sdk@main
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.branch }}
          FEEDNAME: nikki
          PACKAGES: luci-app-nikki nikki
          NO_REFRESH_CHECK: true

      - name: Extract package versions
        id: extract_version
        run: |
          set -e

          PKG_DIR="bin/packages/${{ matrix.arch }}/nikki"

          # Ambil versi dari luci-app-nikki
          PKG_FILE_LUCI=$(find "$PKG_DIR" -name 'luci-app-nikki_*.ipk' | head -n 1)
          if [[ -z "$PKG_FILE_LUCI" ]]; then
            echo "❌ luci-app-nikki package file not found!"
            exit 1
          fi
          VERSION_LUCI=$(basename "$PKG_FILE_LUCI" | sed -E 's/^luci-app-nikki_([^_]+)_.*\.ipk/\1/')
          echo "version_luci=$VERSION_LUCI" >> $GITHUB_OUTPUT

          # Ambil versi dari nikki
          PKG_FILE_NIKKI=$(find "$PKG_DIR" -name 'nikki_*.ipk' | head -n 1)
          if [[ -z "$PKG_FILE_NIKKI" ]]; then
            echo "❌ nikki package file not found!"
            exit 1
          fi
          VERSION_NIKKI=$(basename "$PKG_FILE_NIKKI" | sed -E 's/^nikki_([^_]+)_.*\.ipk/\1/')
          echo "version_nikki=$VERSION_NIKKI" >> $GITHUB_OUTPUT

      - name: Create release filename and tag
        id: release_meta
        run: |
          VERSION_LUCI="${{ steps.extract_version.outputs.version_luci }}"
          VERSION_NIKKI="${{ steps.extract_version.outputs.version_nikki }}"

          REL_NAME="Nikki-TProxy-${VERSION_LUCI}_${VERSION_NIKKI}_${{ matrix.arch }}-${{ matrix.branch }}"

          # Untuk tag, ubah spasi, underscore, tilde menjadi dash
          TAG_NAME=$(echo "$REL_NAME" | tr ' _~' '---')

          echo "relname=$REL_NAME" >> $GITHUB_OUTPUT
          echo "tagname=$TAG_NAME" >> $GITHUB_OUTPUT

      - name: Compress .ipk files
        run: |
          mkdir -p output
          cp bin/packages/${{ matrix.arch }}/nikki/*.ipk output/
          zip -j ${{ steps.release_meta.outputs.relname }}.zip output/*.ipk

      - name: Create empty commit and tag
        env:
          GIT_TAG: ${{ steps.release_meta.outputs.tagname }}
          GIT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git fetch origin
          git checkout --orphan temp-release-branch
          git rm -rf .
          git commit --allow-empty -m "Empty commit for release"

          git tag "$GIT_TAG"
          git push "https://${GIT_TOKEN}@github.com/${{ github.repository }}" "$GIT_TAG"

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          tag_name: ${{ steps.release_meta.outputs.tagname }}
          release_name: ${{ steps.release_meta.outputs.relname }}
          draft: false
          prerelease: false

      - name: Upload ZIP to GitHub Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.release_meta.outputs.relname }}.zip
          asset_name: ${{ steps.release_meta.outputs.relname }}.zip
          asset_content_type: application/zip
